config/routes.rb
Rails.application.routes.draw do

  root 'providers#index'

  resources :clients
  resources :providers
  resources :projects

end

app/models/client.rb
class Client < ActiveRecord::Base
  validates :name, :email, presence: true
  validates :email, uniqueness: true
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :name, :brief, presence: true
end

app/models/provider.rb
class Provider < ActiveRecord::Base

  validates :name, :email, presence: true
  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController

  def index
    @providers = Provider.all
  end

  def new
    @provider = Provider.new
  end

  def create
    @provider = Provider.new(provider_params)
    if @provider.save
      redirect_to(@provider, :notice => 'Post was successfully created.')
    else
      render :action => "new"
    end
  end

  def show
    @provider = Provider.find(params[:id])
  end

  def edit
    @provider = Provider.find(params[:id])
  end

  def update
    @provider = Provider.find(params[:id])

    if @provider.update(provider_params)
      redirect_to @provider
    else
      render 'edit'
    end
  end

  def destroy
    @provider = Provider.find(params[:id])
    @provider.destroy

    redirect_to providers_path
  end

  private

  def provider_params
    params.require(:provider).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProjectAtlantis</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/providers/_form.html.erb
<div class="row">
  <%= form.label :name %>
  <%= form.text_field :name %>
</div>

<div class="row">
  <%= form.label :email %>
  <%= form.text_field :email %>
</div>

<div class="row">
  <%= form.submit %>
</div>

app/views/providers/_provider.html.erb
<p>Provider <%= provider.id %></p>
<p><%= provider.name %></p>
<p><%= provider.email %></p>
<%= link_to t('providers.edit_provider'), edit_provider_path(provider)%>
<%= link_to t('providers.destroy_provider'), provider_path(provider),
            method: :delete,
            data: { confirm: 'Are you sure?' } %>

app/views/providers/edit.html.erb
<div class="container">
  <div class="container__header">
    <%= t('providers.edit_provider') %>
  </div>

  <% if @provider.errors.any? %>
      <ul class="errors">
        <% @provider.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
      </ul>
  <% end %>

  <div class="container__body">
    <%= form_for @provider do |f| %>
        <%= render :partial => 'form', :locals => {form: f} %>
    <% end %>
  </div>
</div>

app/views/providers/index.html.erb
<div class="container">
  <div class="container__head">
    <%= link_to t('providers.new_provider'), new_provider_path %>
  </div>

  <table>
    <% if @providers.any? %>
        <%= render @providers %>
    <% else %>
    <tr>
      <%= t('providers.no_providers') %>
    </tr>
    <% end %>
  </table>
</div>

app/views/providers/new.html.erb
<div class="container">
  <div class="container__header">
    <%= t('providers.new_provider') %>
  </div>

  <% if @provider.errors.any? %>
    <ul class="errors">
      <% @provider.errors.full_messages.each do |message| %>
          <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="container__body">
    <%= form_for @provider do |f| %>
        <%= render :partial => 'form', :locals => {form: f} %>
    <% end %>
  </div>
</div>

app/views/providers/show.html.erb
<%= render @provider %>